### ISSUE TITLE
The GpuBoxDemo crashed on Linux

### ISSUE THREAD

**Issue by joen66** [erwincoumans/experiments#10]
The GpuBoxDemo will crash on Linux, but the GpuCompoundDemo won't.

**Comment by joen66** [comment]
There maybe a bug in the narrow phase during the collision detection because the program can run until the output number of broad phase is not zero.

**Comment by erwincoumans** [comment]
The GpuDemo has never been tested or implemented on Linux. (only Mac OSX and Windows version is implemented).

Did you implement a Linux version?

**Comment by joen66** [comment]
Right, I want to do it :), but the GpuDemo1 does not work now.

**Comment by joen66** [comment]
Sorry, I have a misunderstanding, and corrected the fault (Sphere version -> GpuCompoundDemo and GpuDemo1 version -> GpuBoxDemo) now.

**Comment by erwincoumans** [comment]
The Linux version is not tested or supported yet. Unless you want to help fixing the issue, let's close the issue until we start supporting Linux.

**Comment by joen66** [comment]
I want to help fixing the issue, and porting to Linux from Mac version.

**Comment by joen66** [comment]
The GpuBoxDemo can work on Linux now, and demo video: http://www.youtube.com/watch?v=CsMGM27zMC0&feature=youtu.be
The codes needs some reorganization for commit, and will create a branch and be submitted after the Chinese NEW Year.

**Comment by erwincoumans** [comment]
latest revision has a working Linux version:
https://github.com/erwincoumans/experiments/commit/a29e018d1ba63ff8c1b4a31e8fb71abecbbc2495
